### ISSUE TITLE
Delete old events

### ISSUE THREAD

**Issue by alinebastos** [alinebastos/women-dev-conferences#4]
Delete old events from this page:
https://github.com/alinebastos/women-dev-conferences/blob/master/FutureEvents.md

**Comment by AnnaDodson** [comment]
Would it be ok if I looked at this one?

**Comment by alinebastos** [comment]
Of course :)

**Comment by alinebastos** [comment]
Could you assign yourself to this issue?

**Comment by AnnaDodson** [comment]
I don't think I can as I'm not a maintainer: https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by alinebastos** [comment]
That's no problem :)
